defaults:
  - data: baseline
  - model: clip_vit_b32
  - optimizer: adamw
  - scheduler: cosine
  - loss: infonce
  - random_seed: random_seed
  - experiment: null
  - _self_

project: avito_visual_search
device: auto  # auto | cuda | cpu
output_dir: ${hydra:runtime.output_dir}

hydra:
  run:
    dir: experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra:job.name}
  job:
    chdir: false  # рабочая директория автоматически меняется на папку запуска