epochs: 5
gradient_accumulation: 1
max_grad_norm: 1.0
checkpoint_every: 1000

optimizer:
  _target_: torch.optim.AdamW
  lr: 5e-6
  weight_decay: 0.01
  eps: 1e-8

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.epochs}
  eta_min: 1e-7
